### ISSUE TITLE
Reloading?

### ISSUE THREAD

**Issue by skevy** [s-a/iron-node#10]
I know I can hit Command-R to reload the code...but what about integrating some type of mechanism to auto reload code on file change? Or maybe integrate with something already built, like nodemon?

Thoughts?

**Comment by s-a** [comment]
Such a feature is not planed. I think it does not hurt if we press ctrl+r to reload since we always have to switch to the ironNode window for the debugging process. Maybe you are annoyed be the close process on uncaught exceptions at start?  
This behavior has changed since v1.0.8 https://github.com/s-a/iron-node/releases/tag/v1.1.8

These file and folder watching processes often result in unstable and slow workflows since not every developer is using a power mac.
