### ISSUE TITLE
new installation requieres install -g and still can't start

### ISSUE THREAD

**Issue by vkuehn** [s-a/iron-node#127]
when installing with sudo npm iron-node -g on a ubtuntu 14.04 x64 starting iron-node causes 

fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/usr/lib/node_modules/iron-node/bin/iron-node.env.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.writeFileSync (fs.js:1333:33)
    at /usr/lib/node_modules/iron-node/bin/run.js:41:5
    at onStdIn (/usr/lib/node_modules/iron-node/bin/run.js:17:3)
    at Object.<anonymous> (/usr/lib/node_modules/iron-node/bin/run.js:33:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)

the file actually didn't exist and creating it with chmod 755 didn't brin a solution...any idea ?

**Comment by s-a** [comment]
iron-node try to write this file to transfer your current node environment
to forthcoming electron instance. Try `sudo iron-node...` or install
iron-node for the user you use to make sure you have read and write access
to `iron-node.env.json`

Am 02.02.2017 9:01 nachm. schrieb "vkuehn" <notifications@github.com>:

when installing with sudo npm iron-node -g on a ubtuntu 14.04 x64 starting
iron-node causes

fs.js:640
return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
^

Error: EACCES: permission denied, open '/usr/lib/node_modules/iron-
node/bin/iron-node.env.json'
at Error (native)
at Object.fs.openSync (fs.js:640:18)
at Object.fs.writeFileSync (fs.js:1333:33)
at /usr/lib/node_modules/iron-node/bin/run.js:41:5
at onStdIn (/usr/lib/node_modules/iron-node/bin/run.js:17:3)
at Object. (/usr/lib/node_modules/iron-node/bin/run.js:33:1)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)

the file actually didn't exist and creating it with chmod 755 didn#t brin a
solution...any idea ?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/s-a/iron-node/issues/127>, or mute the thread

**Comment by s-a** [comment]
We should move `iron-node.env.json` to system` s temporary folder.

**Comment by s-a** [comment]
Well I simply use ( without `sudo` ) `npm i -g iron-node` on Ubuntu .

**Comment by vkuehn** [comment]
on ubuntu you don't have write access to /usr/lib/node_modules.... so -g won't work unless you have made a manual configuration to use a different folder for node-modules.Therefore I see again
npm ERR! Please try running this command again as root/Administrator.
So I have to use iron-node always with root rights

**Comment by s-a** [comment]
We should change the location of `iron-node.env.json` to temporary folder of operating system. Can you send a PR?

**Comment by vkuehn** [comment]
uuuh not sure if I am the right person to do here PR's....I'll look at the weekend for that

**Comment by s-a** [comment]
Great. You are the right person to do PRs. Just deployed https://github.com/s-a/iron-node/releases/tag/v3.0.18. `vkuehn.haveNiceWeekend()`. 😄

**Comment by vkuehn** [comment]
thanks hopefully it was the right approach....
