### ISSUE TITLE
Duplicate with node-inspector?

### ISSUE THREAD

**Issue by CatTail** [s-a/iron-node#18]
What's the difference? advantage? OR purpose?

[node-inspector](https://github.com/node-inspector/node-inspector)

**Comment by s-a** [comment]
Well Node inspector often crashes on my machines so it feels a little bit buggy. It also have some more problems in my eyes. Setting a break-point, attaching the debugger to node process is extreme time consuming even if the debugger crashes very often.  
I prefer ironNode because I do not have to care about this "workflow" when I simply start my node project the same way I would do it with `node`. It 's also efficient to press `ctrl+r` to simply restart the code. 

While ironNode works completely different it is definitely not a dublicate. You can watch the workflow in this very simple 2 minute demo https://www.youtube.com/watch?v=pxq6zdfJeNI

**Comment by kshirish** [comment]
Still not convinced how it is better( or different ) than node-inspector?

**Comment by s-a** [comment]
I'm sorry for that. I will close this issue but feel free to continue this discussion. :+1:

**Comment by hellboy81** [comment]
Is there feature comparison table?

**Comment by s-a** [comment]
Just created https://github.com/s-a/iron-node/blob/master/docs/FEATURES.md I hope this will help.

**Comment by nakedcity** [comment]
Well guys node-inspector was for me really slow and it does not work with node v6 :) thanks guys for iron-node!

**Comment by derakhshanfar** [comment]
thanks for create this libray.. its great.. node inspector has a lot of open issue
