### ISSUE TITLE
Live reload or support nodemon

### ISSUE THREAD

**Issue by Ti-webdev** [s-a/iron-node#47]
I ran this:

``` zsh
iron-node $(whence -f nodemon) index.js 
```

and `debugger` has not been caught

**Comment by Ti-webdev** [comment]
#10 is related

**Comment by s-a** [comment]
I am not sure `nodemon` starts an own process instance of node to monitor file system changes. If so this use case is outside of accessibility. The reason why your break-point will not reach is that ironNode needs a JavaScript file as an entry point as described at https://github.com/s-a/iron-node/blob/master/docs/DEBUG-NODEJS-COMMANDLINE-APPS.md. 
For a quick success : Can you check this doc out?

So far there is no monitoring on the road map. As I wrote on #10 

> These file and folder watching processes often result in unstable and slow workflows since not every developer is using a power mac.

Since a while ironNode supports application settings. So I can imagine to work on experimental features, but currently I have not time to work on monitoring. From my point of view monitoring makes sense for a support while development. But not really while debugging because we always have to switch back to debugger GUI for the debugging process.

**Comment by s-a** [comment]
Will close this issue until there is no feedback. We can re open it when clarifed if nodemon allows debugging.
