### ISSUE TITLE
Not working with node 5.1.1 and edgejs on windows

### ISSUE THREAD

**Issue by eblumenfeld** [s-a/iron-node#60]
Hi,

I'm finding that I can run an app with node.exe, but with iron-node it gives me
an error that edgejs wasn't compiled for node.js version 2.3.1.

Could be possible that this is because iron-node works with the old io.js?

Regards,

Eduardo

**Comment by s-a** [comment]
Yes, but it results more from the fact that there is a different v8 engine in electron than an old node version. 
@remy faced also such a problem but have more trouble I try to fix curently. You need to recompile edgejs with `-compile` as described at #58 .

Since [Electron v0.31.0](https://github.com/atom/electron/releases/tag/v0.31.0) There was a breaking change ...

> Most native modules are broken because of io.js upgrade, module writers need to use NAN v2 to rewrite the modules.

This is the reason I never upgraded Electron. Curently Electron is using Node.js v4.1.1. so I think it could be save to upgrade the next time. 

You can try yourself to upgrade electron within ironNode.
- clone this repo
- change electron dependecy to `0.34.0` in `package.json` 
- type `npm install -g` from cloned folder
  After that you have a good chance to use your "old" native modules without recompiling the binaries. 
  Feedback is appreciated :+1: 

I d like to test this and upgrade the repo but unfortunately my dev machine ' s node-gyp environment is broken since upgrade to node 4. https://github.com/nodejs/node-gyp/issues/778 I will try to work on that this weekend.

**Comment by eblumenfeld** [comment]
@s-a Thank you very much for the quick answer, will try to see if I can install from the cloned repo later in the week.

**Comment by s-a** [comment]
@eblumenfeld @remy any new s about this? I am still upgrading from Node 0.11 to Node 4\5. Seems there are heavy movements o.O

Hope I can fix it this weekend.

**Comment by hotoo** [comment]
+1 atom/electron#3677

**Comment by s-a** [comment]
I was able to recompile the binaries with `iron-node --compile` in the newest version,

But I still get the error: 
`Error: The edge module has not been pre-compiled for node.js version v5.1.1. You must build a custom version of edge.node. Please refer to https://github.com/tjanczuk/edge for building instructions.(…)`

My custom `require.js` does not detect target for compiled binaries . Could need some help here. The question is: How to get native binary from required module
![image](https://cloud.githubusercontent.com/assets/1270662/11760852/927f65a4-a0ac-11e5-95a1-ae338040a26d.png)

In this case edgejs compiled 2 binaries:
c:\git\require\node_modules\edge\bin\win32-ia32-v8-4.7\edge_coreclr.node
c:\git\require\node_modules\edge\bin\win32-ia32-v8-4.7\edge_nativeclr.node

**Comment by s-a** [comment]
https://github.com/tjanczuk/edge/issues/363

**Comment by s-a** [comment]
Sorry. I opened a ticket at edgejs and close this until this issue is out of my scope.
